name: Bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** Before submitting:
        - Is your OpenDTU up to date? [Releases](https://github.com/tbnobody/OpenDTU/releases)  
